config/routes.rb
Imls::Application.routes.draw do
  root :to => "catalog#index"

  Blacklight.add_routes(self)

  devise_for :users

end

app/models/solr_document.rb
# -*- encoding : utf-8 -*-
class SolrDocument

  include Blacklight::Solr::Document
  include BlacklightHighlight::SolrDocumentExtension


  # self.unique_key = 'id'

  # The following shows how to setup this blacklight document to display marc documents
  extension_parameters[:marc_source_field] = :marc_display
  extension_parameters[:marc_format_type] = :marcxml
  use_extension( Blacklight::Solr::Document::Marc) do |document|
    document.key?( :marc_display  )
  end

  # Email uses the semantic field mappings below to generate the body of an email.
  SolrDocument.use_extension( Blacklight::Solr::Document::Email )

  # SMS uses the semantic field mappings below to generate the body of an SMS email.
  SolrDocument.use_extension( Blacklight::Solr::Document::Sms )

  # DublinCore uses the semantic field mappings below to assemble an OAI-compliant Dublin Core document
  # Semantic mappings of solr stored fields. Fields may be multi or
  # single valued. See Blacklight::Solr::Document::ExtendableClassMethods#field_semantics
  # and Blacklight::Solr::Document#to_semantic_values
  # Recommendation: Use field names from Dublin Core
  use_extension( Blacklight::Solr::Document::DublinCore)
  field_semantics.merge!(
                         :author => "author_display",
                         :language => "language_facet",
                         :format => "format"
                         )
end

app/models/user.rb
class User < ActiveRecord::Base
# Connects this user object to Blacklights Bookmarks and Folders. 
 include Blacklight::User
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier for
  # the account. 
  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include Blacklight::Controller
  # Please be sure to impelement current_user and user_session. Blacklight depends on 
  # these methods in order to perform user specific actions. 

  protect_from_forgery

  def layout_name
    "application"
  end
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController

  include Blacklight::Catalog
  include BlacklightHighlight::ControllerExtension


  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = {
      :qt => 'search',
      :rows => 10
    }

    # solr field configuration for search results/index views
    config.index.show_link = 'title'
    config.index.record_display_type = 'format'
    config.add_index_field 'creator', :label => 'Creator:'
    config.add_index_field 'subject', :label => 'Subject:'
    config.add_index_field 'date', :label => 'Date:'


    # solr field configuration for document/show views
    config.show.html_title = 'title'
    config.show.heading = 'title'
    config.show.display_type = 'format'
    config.add_show_field 'creator', :label => 'Creator:'
    config.add_show_field 'subject', :label => 'Subject:'
    config.add_show_field 'description', :label => 'Description:'
    config.add_show_field 'publisher', :label => 'Publisher:'
    config.add_show_field 'date', :label => 'Date:'
    config.add_show_field 'type', :label => 'Type:'
    config.add_show_field 'format', :label => 'Format:'
    config.add_show_field 'identifier', :label => 'Identifier:'


    # solr fields that will be treated as facets by the blacklight application
    config.add_facet_field 'type_facet', :label => 'Type'
    config.add_facet_field 'format_facet', :label => 'Format'
    config.add_facet_field 'date_facet', :label => 'Date'
    # Have BL send all facet field names to Solr
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    config.add_search_field 'all_fields', :label => 'All Fields'
    config.add_search_field('title') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'title' }
      field.solr_local_parameters = {
        :qf => '$title_qf',
        :pf => '$title_pf'
      }
    end
    config.add_search_field('creator') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'creator' }
      field.solr_local_parameters = {
        :qf => '$creator_qf',
        :pf => '$creator_pf'
      }
    end
    config.add_search_field('subject') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'subject' }
      field.solr_local_parameters = {
        :qf => '$subject_qf',
        :pf => '$subject_pf'
      }
    end

    # "sort results by" select (pulldown)
    config.add_sort_field 'score desc, title_sort asc', :label => 'Relevance'
    config.add_sort_field 'date_sort desc', :label => 'Date'
    config.add_sort_field 'title_sort asc', :label => 'Title'

    # If there are more than this many search results, no spelling ("did you
    # mean") suggestion is offered.
    config.spell_max = 5


    # advanced search configuration
    config.advanced_search = {
      :form_solr_parameters => {
        'facet.field' => %w[type_facet format_facet date_facet]
      }
    }

    # fields available only from advanced search
    config.add_search_field('description') do |field|
      field.include_in_simple_select = false
    end
    config.add_search_field('publisher') do |field|
      field.include_in_simple_select = false
    end
    config.add_search_field('source') do |field|
      field.include_in_simple_select = false
    end
    config.add_search_field('relation') do |field|
      field.include_in_simple_select = false
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def onload_method
    if params[:q].blank? && params[:f].blank? && params[:id].nil?
      "$('input#q').focus();"
    end
  end
end

app/views/catalog/_home.html.haml
= render 'home_text'
= render 'search_form'

- sidebar_items << capture do
  = render 'facets'

app/views/catalog/_home_text.html.haml
%h1 Connecting Presidential Collections

%blockquote Mission Statement: We are the roxorz!

app/views/catalog/_search_form.html.erb
<div id="search" class="search">
  <%= form_tag catalog_index_path, :method => :get do %>
    <h2 class="search"><%= label_tag(:q, "Search ") %></h2>
    <%= text_field_tag :q, params[:q], :class => "q" %>
    <%= label_tag(:search_field, " in ") %>
    <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => "Targeted search options", :class=>"search_field") %>
    
    <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>        
    
    <%= submit_tag 'search', :class=>'submit' %>
  <% end %>
  <%= link_to 'Advanced', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search"%> 
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= h(@page_title || 'IMLS')
    = favicon_link_tag asset_path('favicon.ico')
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = raw render_head_content

  %body{onload: onload_method, class: render_body_class.html_safe}
    #page
      #hd
        #logo
          %h1.site_title
            = link_to application_name, '/'
            = content_tag(:span, 'Search Results', id: :results_text) if (params[:controller] == 'catalog' and !params[:id])
        #user_util_links= render '/user_util_links'

      #bd
        #main
          #main_container
            = render '/flash_msg'
            = yield
        #sidebar= sidebar_items.join.html_safe

      #ft= raw @footer